---
- name: Deploy React App Front-end Build
  connection: ssh
  gather_facts: false
  hosts: all
  vars:
    repo_folder: /home/ansible/build-dir
    live_folder: /home/ansible/prod-dir
    repo_name: ssWitcher/nodeApp
  tasks:
  - git:
      repo: ssh://git@github.com/{{ repo_name }}.git
      dest: "{{ repo_folder }}"
      update: yes
  - name: Install dependencies
    yarn:
      path: "{{ repo_folder }}"